# Generated by Django 3.2.4 on 2023-09-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_booknow'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='userid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
